# -*- coding: utf-8 -*-
"""exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etcNuxwr48QXMdS3eP3Ut9-i2gI48UbE
"""

import math

def q_solve(a, b, c):
    if a == 0:
        if b == 0:
            if c == 0:
                return "infinitely many solutions"
            else:
                return "no solution"
        else:
            return [-c / b]

    discriminant = b**2 - 4*a*c

    if discriminant < 0:
        return "no real solution"
    elif discriminant == 0:
        x = -b / (2*a)
        return [x]
    else:
        x1 = (-b + math.sqrt(discriminant)) / (2*a)
        x2 = (-b - math.sqrt(discriminant)) / (2*a)
        return [x1, x2]

print(q_solve(1, -5, 6))   # x^2 - 5x + 6 = 0 -> 2, 3
print(q_solve(1, 2, 1))    # x^2 + 2x + 1 = 0 -> -1
print(q_solve(1, 0, 1))    # x^2 + 1 = 0 -> no real solution
print(q_solve(0, 2, -4))   # 2x - 4 = 0 -> 2